name: catan_master
version: 0.0.2
description: "A clean & simple Catan player & game data manager"

dependencies:
  bloc: ^7.2.1
  dartz: ^0.10.0
  datetime_picker_formfield: ^2.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_polygon: ^0.3.0+1
  fluttertoast: ^8.0.8
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  provider: ^6.0.1
  collection: ^1.15.0

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  hive_generator:
  json_serializable:
  test:

environment:
  sdk: '>=2.12.0 <3.0.0'

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png

flutter:
  uses-material-design: true
  fonts:
    - family: Catan
      fonts:
        - asset: fonts/Catan.ttf