name: catan_master
version: 0.0.2
description: "A clean & simple Catan player & game data manager"

dependencies:
  bloc: ^6.1.3
  dartz: ^0.9.2
  datetime_picker_formfield: ^2.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.3
  fluttertoast: ^7.1.8
  freezed_annotation: ^0.14.0
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  intl: ^0.17.0
  json_annotation: ^4.0.0
  polygon_clipper: ^1.0.2
  provider: ^4.3.3

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  json_serializable: ^4.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png

flutter:
  uses-material-design: true
  fonts:
    -
          family: Catan
          fonts:
            -
                  asset: fonts/Catan.ttf
