name: catan_master
description: A clean & simple Catan player & game data manager

version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Firebase
#  firebase_core: ^1.0.0
#  firebase_auth: ^1.0.0
#  firebase_database: ^6.1.0

  datetime_picker_formfield: ^2.0.0
  flutter_bloc: ^6.1.3
  bloc: ^6.1.3
  provider: ^4.3.3
  equatable: ^2.0.0
  json_annotation: ^4.0.0
  freezed_annotation: ^0.14.0
  polygon_clipper: ^1.0.2
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  dartz: ^0.9.2
  intl: ^0.17.0
#  flutter_form_builder: ^4.2.0
  fluttertoast: ^7.1.8
#  path_provider: ^1.6.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^4.0.2
  hive_generator: ^0.8.2
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  fonts:
   - family:  Catan
     fonts:
      - asset: fonts/Catan.ttf
