name: catan_master
version: 0.0.2
description: "A clean & simple Catan player & game data manager"

dependencies:
  bloc: ^7.0.0-nullsafety.4
  dartz: ^0.10.0-nullsafety.1
  datetime_picker_formfield: ^2.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0-nullsafety.5
  fluttertoast: ^8.0.1-nullsafety.0
  freezed_annotation: ^0.14.1
  hive: ^1.6.0-nullsafety.2
  hive_flutter: ^1.0.0-nullsafety.0
  intl: ^0.17.0
  json_annotation: ^4.0.0
  provider: ^5.0.0

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  json_serializable: ^4.0.2
  test: ^1.16.5

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png

flutter:
  uses-material-design: true
  fonts:
    -
          family: Catan
          fonts:
            -
                  asset: fonts/Catan.ttf
