name: catan_master
version: 0.0.4+4
description: "A clean & simple Catan player & game data manager"

dependencies:
  bloc: ^8.0.1
  collection: ^1.15.0
  dartz: ^0.10.1
  datetime_picker_formfield: ^2.0.0
  device_info_plus: ^3.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_polygon: ^0.3.0+2
  fluttertoast: ^8.0.8
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  package_info_plus: ^1.3.0
  provider: ^6.0.1
  share_plus: ^3.0.4
  stream_transform: ^2.0.0
  url_launcher: ^6.0.17

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  hive_generator:
  json_serializable:
  test:

environment:
  sdk: '>=2.15.0 <3.0.0'

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png

flutter:
  uses-material-design: true
  fonts:
    - family: Catan
      fonts:
        - asset: fonts/Catan.ttf